export const playerFAQs = [
  { question: "What is Forehand used for right now?", answer: "Forehand (MVP) helps you create/join tournaments, view brackets, and do live scoring for Pickleball tournaments." },
  { question: "Is Forehand only for Pickleball?", answer: "Yes, currently only Pickleball. We are planning to add few other sports soon." },
  { question: "Do I need an account to browse tournaments?", answer: "Yes, Sign up with any of your google account, answer few questions and you’re all set." },
  { question: "How do I sign up / log in?", answer: "Use your google account." },
  { question: "Can I use the same account on multiple devices?", answer: "Usually yes, but only one active session may be stable at a time. If scores aren’t syncing, log out on the other device." },
  { question: "How do I edit my profile (name, phone, skill level, city)?", answer: "Go to Profile then click on ‘Edit Profile’ button." },
  { question: "Can I delete my account or my data?", answer: "Not as of now, you can request deletion via support. Note: tournament results may remain as records even if your account is removed (depending on policy)." },
  { question: "Will scores of quick match effect my quick stats data?", answer: "No, data for quick matches are not recorded anywhere." },
  { question: "What’s in history tab under tournament page?", answer: "Tournaments that are ended will be shown there." },
  { question: "What’s shown in live feed.", answer: "Live matches for tournaments around you, not necessarily what you have participated in." },
  { question: "How do I find a tournament to join?", answer: "Use the tournaments list in the dedicated page you’ll find in the bottom nav bar or a direct tournament link/code shared by the organizer." },
  { question: "Can I search by city, date, venue, organizer, or level?", answer: "Yes, Use the filter option in tournament page." },
  { question: "Can I still view the event and tournamen details if not particpating.", answer: "Yes you can view them." },
  { question: "How do I join a tournament?", answer: "Open the tournament page → tap Register → confirm details." },
  { question: "I joined, but my name is not showing in the participant list—why?", answer: "Refresh the page. If still missing: registration may be pending approval, network issue occurred, or your join didn’t submit." },
  { question: "What if I joined the wrong tournament—can I leave?", answer: "If there’s a Leave/Withdraw button, use it before the bracket is generated. If not, message the organizer to remove you." },
  { question: "Can I join multiple tournaments at once?", answer: "Yes—you can register for multiple tournaments, but be careful about schedule conflicts." },
  { question: "Can I join as a doubles team? If yes, how do I add my partner?", answer: "Yes, you can add your partners phone number, the’ll receive the notification in the app. They must have an account on forehand." },
  { question: "What are eligibility rules (age/skill/club membership)?", answer: "Eligibility depends on each tournament. Check the tournament rules/description or ask the organizer." },
  { question: "Is there a fee to join? If yes, how do payments work?", answer: "2 options for payment: Pay by the QR or pay at the venue directly." },
  { question: "What happens if the tournament is full? Is there a waitlist?", answer: "Organiser can confirm your registration from their end, it’ll be visible in app on the event page." },
  { question: "Where do I see my match schedule?", answer: "Inside the event page under Fixtures and Matches." },
  { question: "When will the bracket be generated?", answer: "Usually after registrations close or when the organizer clicks Generate Bracket." },
  { question: "Why is my match not scheduled yet?", answer: "Bracket not generated, not enough participants, organizer hasn’t started the tournament, or you’re in a slot with a bye." },
  { question: "How are byes decided?", answer: "Commonly automatic (based on bracket size). Sometimes seeded players get byes, depending on organizer settings." },
  { question: "Can the bracket change after it’s published?", answer: "No." },
  { question: "What do I do if my opponent doesn’t show up?", answer: "Inform the organizer. They may mark it as a walkover/no-show and advance you." },
  { question: "Can I see the full bracket and upcoming matches?", answer: "Yes, tournament bracket view shows the full structure and winners advancing." },
  { question: "What do “Round 1 / Quarterfinal / Semifinal / Final” mean?", answer: "They are stages of a knockout bracket. The number depends on participants (e.g., 16 players → Round of 16, QF, SF, Final)." },
  { question: "Who is allowed to score—player, organizer, or a referee?", answer: "Either scorer or the organizer." },
  { question: "Can I pause scoring mid-match?", answer: "Yes, you can ask the scorer to pause it." },
  { question: "Can I resume scoring from where it stopped?", answer: "Yes, scorer can restart." },
  { question: "Where can I see match results and my tournament progress?", answer: "Tournament bracket and match list show winners and next rounds." },
  { question: "Why does my result show wrong / missing?", answer: "Score not submitted, match left in draft, sync issue, or organizer edited bracket. Refresh and contact organizer." },
  { question: "Can results be edited after submission? Who can edit them?", answer: "No." },
  { question: "Will there be ratings/leaderboards in the future?", answer: "Likely, but not part of the current MVP unless explicitly built." },
  { question: "How do I contact the organizer?", answer: "Use the organizer contact shown on tournament page (or ask in the venue/WhatsApp group if that’s how they coordinate)." },
  { question: "Where do I see tournament rules (format, scoring, reporting time)?", answer: "On tournament details/rules section. If missing, ask organizer before playing." },
  { question: "What happens if the organizer changes rules mid-tournament?", answer: "Organizer should announce changes. If it affects fairness, players can request rollback or clarification." },
  { question: "How do I report a bug or request a feature?", answer: "Use in-app support e-mail." },
  { question: "What information should I include when reporting an issue?", answer: "Tournament name/code, your account name/phone, match round, what you expected, what happened, and screenshots." },
  { question: "What if my phone dies or app crashes during a match?", answer: "Reopen the app and go back to the match. If it doesn’t restore, the organizer can re-open or re-enter the current score." },
  { question: "What if there is no internet at the venue? Does live scoring work offline?", answer: "MVPs typically require internet. If offline scoring isn’t supported, keep score manually and update when connection returns (or ask organizer to update)." },
  { question: "Can I download/share my results?", answer: "If sharing exists, you can share a link/screenshot. Export may come later." },
  { question: "Do I get a player profile with my match history?", answer: "Often yes in concept, but MVP may only show tournament participation. Full profile/history typically expands over time." },
  { question: "Do I get notifications when my match is about to start?", answer: "If notifications are enabled in MVP, you’ll get alerts. Otherwise, rely on organizer announcements." },
  { question: "Can I turn off notifications?", answer: "Yes—via app settings or phone notification settings." },
  { question: "I’m not receiving notifications—how do I fix it?", answer: "Enable notifications in phone settings, ensure you’re logged in, and check battery optimization settings." },
];

export const orgFAQs = [
  { question: "Do I need a separate organizer account or same login works?", answer: "You need to create an organisation after creating a ind. player account and then you can add other related members to that org. if needed." },
  { question: "How do I create my first tournament?", answer: "Org. profile → Tournament Page → ‘+’ icon at the top right corner → Enter tournaments details → publish/open registrations." },
  { question: "Can I create multiple tournaments under one account?", answer: "Yes, organizers can run multiple tournaments at once." },
  { question: "Can I add co-organizers/admins?", answer: "Yes, Profile → Add members" },
  { question: "Can I restrict who can create tournaments (private vs public)?", answer: "Only organizers and org. member can create tournaments." },
  { question: "Can I set registration start/end dates?", answer: "Yes, you can manage it manually." },
  { question: "Can I cap participants?", answer: "No, You can save and proceed participants when all your seats are filled manually." },
  { question: "Can I collect entry fees? How does payment and refund work?", answer: "You have 2 options: Directly at your UPI, QR code can be uploaded while creating the tournament or at the venue." },
  { question: "Can I create categories (Men’s Singles, Women’s Singles, etc.)?", answer: "Yes, you can create events for different categories." },
  { question: "Can I run doubles? How do teams register?", answer: "Yes, you can change the participation type to doubles, player enter their partner phone number to register." },
  { question: "Can I set scoring rules (points per game, win-by-2, etc.)?", answer: "Yes, we have basic adjustments as of now like sets, points, etc." },
  { question: "Can I add rules text / instructions visible to players?", answer: "Yes." },
  { question: "Can I add sponsor logos/banners?", answer: "Not as of now." },
  { question: "Can I create a tournament as invite-only with a code?", answer: "No, tournaments are open for all as of now. Anyone can register." },
  { question: "How do I share the tournament link/code with players?", answer: "You’ll get an share option with a QR code to share tournaments." },
  { question: "Players are unable to join, what should I check first?", answer: "Tournament/event is Open, registration date active?, capacity not full, correct link/code, and player is logged in." },
  { question: "How do I approve/reject registrations?", answer: "There’s an option for managing participants in events page: org. view." },
  { question: "Can I manually add a player to the tournament?", answer: "No, player should have account and self register." },
  { question: "Can I remove a player or disqualify someone?", answer: "Not after finalising participants." },
  { question: "What happens if someone joins with the wrong name/phone?", answer: "Participants can edit their in their profile." },
  { question: "Can I export participant list?", answer: "Not as of now." },
  { question: "When can I generate the bracket?", answer: "After enough players joined and before the tournament starts. You can manually confirm ‘save and proceed’ all the participants before generating bracket." },
  { question: "Can I seed players manually?", answer: "Yes, you can make the fixtures manually." },
  { question: "How are byes handled?", answer: "Auto-assigned when player count isn’t a power of 2. You can explain it as normal bracket math." },
  { question: "Can I regenerate the bracket after players join?", answer: "No, once the brackets are generated, you can’t regenrate." },
  { question: "Can I switch format (single elimination vs round robin) after creation?", answer: "No after creation in MVP. You may need to create a new tournament/event if format changes." },
  { question: "Who can start scoring a match?", answer: "Organizer and/or scorer." },
  { question: "Can I assign a scorer/referee per match?", answer: "Yes. there’s an option for choosing scorer per match." },
  { question: "Can I edit a score if there’s a dispute?", answer: "Yes." },
  { question: "How do I pause, restart, or cancel a match?", answer: "Controls exist, use them. If not, communicate to players and update scoring when resumed." },
  { question: "What if two matches are being scored for the same bracket slot?", answer: "It can not, there’s dedicated time alloted for each match." },
  { question: "What if internet drops mid-match?", answer: "Continue match offline manually and update score when internet returns, or move scoring to a device with better network." },
  { question: "How do I ensure scores are accurate and final?", answer: "Require players to confirm score before submitting. If possible, lock match after submission." },
  { question: "Can I lock results after confirmation?", answer: "Results will be automatically be locked after submitted." },
  { question: "How do I move the tournament to “Started / Live / Completed”?", answer: "It’ll move automatically." },
  { question: "How do I handle delays and rescheduling?", answer: "You can update time for each match." },
  { question: "Can I change match order / assign courts?", answer: "In MVP, You can assign courts and not reorder matches." },
  { question: "How do I track which matches are currently live?", answer: "Use the match list—matches marked “Live/In progress”." },
  { question: "How do I resolve disputes quickly inside the app?", answer: "Pause scoring, hear both players, decide, then update score using organizer override." },
  { question: "How do I publish final results?", answer: "Once final match is completed, the bracket shows winners. Share tournament link or screenshot bracket." },
  { question: "Can I edit final standings after completion?", answer: "No." },
  { question: "Can I export results (PDF/Excel)?", answer: "Not as of now." },
  { question: "Can players view the bracket/results after the event ends?", answer: "Yes, they can view in the event page." },
  { question: "What data is visible to players vs private to organizers?", answer: "Players can see tournament details, bracket, match scores, and participant list. Organizer-only: admin controls, edits/overrides, and possibly contact/payment notes." },
  { question: "How do I report a bug during a live event (urgent support flow)?", answer: "Use the fastest channel (WhatsApp/call/email). Provide tournament link, device type, and what’s broken (scoring/bracket/joining)." },
  { question: "What should I do if a player claims the score is wrong?", answer: "Pause, confirm last agreed score, check with opponent/referee, then edit using organizer override. Log what changed and why." },
  { question: "Does Forehand verify results or is it organizer-controlled?", answer: "In MVP, it’s typically organizer-controlled." },
  { question: "How do I prevent fake players / duplicate registrations?", answer: "Use invite codes, require phone verification, approve registrations manually (if available), and keep a check-in list at venue." },
  { question: "How do I handle walkovers / no-shows?", answer: "Mark match as walkover/no-show and advance the present player. If not built, enter a score consistent with your policy and announce it." },
  { question: "Can I broadcast announcements to all players (time change, court change)?", answer: "If in-app announcements exist, use them. If not, rely on WhatsApp/venue announcements." },
  { question: "Can I duplicate a past tournament to create a new one quickly?", answer: "If “Duplicate” exists, yes. If not, copy details manually when creating a new tournament." },
  { question: "Can I archive a tournament?", answer: "If archive exists, use it for old tournaments. Otherwise just mark completed." }
];
